variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - "$CI_PROJECT_DIR/.cache/pip"

stages:
  - build
  - static-analysis
  - test
  - doc

wheel:3.8:
  image: python:3.8-buster
  stage: build
  before_script:
    - pip install build
  script:
    - python -m build --wheel .
  artifacts:
    paths:
      - dist/
    expire_in: 1 day
  tags:
    - docker

sdist:
  image: python:3.8-buster
  stage: build
  before_script:
    - pip install build
  script:
    - python -m build --sdist .
    - pip install compressai --find-links=dist/
  tags:
    - docker

wheel:3.9:
  extends: wheel:3.8
  image: python:3.7-buster

wheel:3.7:
  extends: wheel:3.8
  image: python:3.7-buster

wheel:3.6:
  extends: wheel:3.8
  image: python:3.6-buster

pylint:
  stage: static-analysis
  image: pytorch/pytorch:1.7.1-cuda11.0-cudnn8-runtime
  before_script:
    - python --version
    - pip install pylint
    - pip install compressai --find-links=dist/
  script:
    - pylint compressai examples
  tags:
    - docker

black:
  stage: static-analysis
  image: python:3-buster
  before_script:
    - python --version
    - pip install black
  script:
    - black --check --diff compressai examples tests
  tags:
    - docker

isort:
  stage: static-analysis
  image: python:3-buster
  before_script:
    - python --version
    - pip install isort
  script:
    - isort --check-only -v compressai examples tests
  tags:
    - docker

test:pytorch-1.5.1:
  stage: test
  image: pytorch/pytorch:1.5.1-cuda10.1-cudnn7-runtime
  before_script:
    - python --version
    - pip install compressai --find-links=dist/
    - pip install click pytest codecov pytest-cov
  script:
    - >
      if [ "$CI_COMMIT_BRANCH" == "master" ]; then
        pytest --cov=compressai -s tests
      else
        pytest --cov=compressai -m "not pretrained" -s tests
      fi
  tags:
    - docker

test:pytorch-1.6.0:
  extends: test:pytorch-1.5.1
  image: pytorch/pytorch:1.6.0-cuda10.1-cudnn7-runtime

test:pytorch-1.7.1:
  extends: test:pytorch-1.5.1
  image: pytorch/pytorch:1.7.1-cuda11.0-cudnn8-runtime

doc:
  stage: doc
  image: pytorch/pytorch:1.7.1-cuda11.0-cudnn8-devel
  before_script:
    - python --version
    - pip install compressai --find-links=dist/
    - cd docs
  script:
    - pip install -r requirements.txt
    - make html
  tags:
    - docker
  # TODO: copy the generated doc to a public webserver
